service: community-backend-serverless-aws

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    MYSQL_HOST: your-rds-instance-endpoint
    MYSQL_USER: your-db-username
    MYSQL_PASSWORD: your-db-password
    MYSQL_DATABASE: forumdb
    S3_BUCKET: your-s3-bucket-name
    DYNAMODB_TABLE: forum-posts

functions:
  getPosts:
    handler: src/handlers/posts.getPosts
    events:
      - http:
          path: posts
          method: get

  createPost:
    handler: src/handlers/posts.createPost
    events:
      - http:
          path: posts
          method: post

  uploadFile:
    handler: src/handlers/upload.uploadFile
    events:
      - http:
          path: upload
          method: post

resources:
  Resources:
    ForumPostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: forum-posts
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

plugins:
  - serverless-offline
  - serverless-plugin-warmup